### ISSUE TITLE
Messages not showing up

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Validator#18]
See http://sandbox.semantic-mediawiki.org/wiki/Mapsdoc_-_leaflet

Maybe old style message registration got dropped altogether? Ping @Nikerabbit @kghbln 

Presumably we can just upgrade and drop the shim...

**Comment by Nikerabbit** [comment]
Why is everything in French? Old style message registration still works in the core.

**Comment by kghbln** [comment]
> Why is everything in French?

It is a French language instance so this is ok. Since the descriptions work there must be another issue with providing the messages for the type.

I believe dropping the shim will not affect this issue though doing so is still a good idea.

**Comment by kghbln** [comment]
> I believe dropping the shim will not affect this issue

sandbox is on 2.2.1 and still worries ...

**Comment by kghbln** [comment]
I cannot tell why these messages still do not roll in. Would be a shame to drop the `#mapsdoc` parser functions instead.

**Comment by JeroenDeDauw** [comment]
Heh... found the issue. It's a bug in Maps, cause by poor naming in ParamProcessor...

**Comment by kghbln** [comment]
Great! Thank you for making this fluffy again!
