### ISSUE TITLE
Error  after install

### ISSUE THREAD

**Issue by Vladsg** [JeroenDeDauw/Validator#24]
When I try install extension "Validator" on the site says:"Exception encountered, of type "Exception"

**Comment by JeroenDeDauw** [comment]
You're going to need more information, such as the version of Validator, how you installed it, the version of MediaWiki and which other extensions you have installed for anyone to help you with that.

**Comment by kghbln** [comment]
Hmm, is https://github.com/SemanticMediaWiki/WhatsNearby/pull/11#issuecomment-255865948 perhaps connected?

**Comment by kghbln** [comment]
> Hmm, is SemanticMediaWiki/WhatsNearby#11 (comment) perhaps connected?

At least it is now recorded as a separate issue: https://github.com/JeroenDeDauw/Validator/issues/26

**Comment by JeroenDeDauw** [comment]
I'm going to close this under the assumption this is about issue #27. Please reopen if not.
