### ISSUE TITLE
Allow to show git hash and time stamp to show on "Special:Version"

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Validator#25]
For some reason this does not show up on [Special:Version](http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version). For other extensions the fix was to change from `__DIR__` to `__FILE__` in the ["wgExtensionCredits" array](https://github.com/JeroenDeDauw/Validator/blob/master/Validator.php#L37). However this is already the case for Validator. See https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/issues/19. Hmm... @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
Is this also broken for Maps 4.0?

**Comment by kghbln** [comment]
> Is this also broken for Maps 4.0?

No, just for Validator, ParserHooks and all the DataValues "extensions", so this is not the cause. The only other thing I can think of is that these are not directly required but fetched by Composer as a dependency.

**Comment by JeroenDeDauw** [comment]
Ah right... if composer gets the code as a zip, then the git version won't show, since the info is not there. Which is fine. Same happens if you manually install something from a zip.

**Comment by kghbln** [comment]
> Ah right... if composer gets the code as a zip, then the git version won't show

Even if one uses `--prefer-source` like I do? Obviously. Is there a way?

**Comment by JeroenDeDauw** [comment]
I don't know of any instances when `--prefer-source` would not fetch the source. Still, it only says `prefer`, so it might be possible. Can you check if what you have on the install where it does not show is a git clone (ie has a `.git` folder in it)?

**Comment by kghbln** [comment]
> Still, it only says `prefer`, so it might be possible.

Indeed, dependencies are not cloned but downloaded even if one uses `--prefer-source`

> Can you check if what you have on the install where it does not show is a git clone (ie has a .git folder in it)?

No, so they were downloaded. Now that I have added `"mediawiki/validator": "@dev",` and `"mediawiki/parser-hooks": "@dev",` to the "composer.local.json" file they get cloned and git hash as well as time stamp show up on "Special:Version".

Thanks for your help along he way here!
