### ISSUE TITLE
PHP 5.3 and 5.4 installation is broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Validator#27]
2.1.0 gets installed for people that have such a PHP version, while it does not support PHP < 5.5. This is because its composer.json wrongly states PHP >= 5.3.

**Comment by JeroenDeDauw** [comment]
I do not know how to fix this

**Comment by JeroenDeDauw** [comment]
http://stackoverflow.com/questions/40271763/correcting-php-version-requirement-in-tagged-release

**Comment by kghbln** [comment]
Why don't you retag to the correct commit or will this be too easy?

**Comment by JeroenDeDauw** [comment]
That is not allowed per SemVer.org

**Comment by kghbln** [comment]
Grump

**Comment by JeroenDeDauw** [comment]
I've now deleted the `2.1.0` tag. If the problem persists, please reopen the issue.
