### ISSUE TITLE
Accessing $wgHooks directly is deprecated since MediaWiki 1.41

### ISSUE THREAD

**Issue by MacFan4000** [JeroenDeDauw/Validator#39]
Deprecated: Accessing $wgHooks directly is deprecated, use HookContainer::getHandlers() or HookContainer::register() instead. [Called from {closure} in /srv/mediawiki/1.41/extensions/Maps/extensions/Validator/Validator.php at line 59] in /srv/mediawiki/1.41/includes/debug/MWDebug.php on line 386

Deprecation warning in MW 1.41 caused by Validator.

seen on https://test.mirabeta.org/wiki/Main_Page

https://test.mirabeta.org/wiki/Special:Version for specific version info

**Comment by paladox** [comment]
Think this was fixed in https://github.com/JeroenDeDauw/Validator/commit/99531b8b3c341c88134f14ddc9467be13f3d975d
